### ISSUE TITLE
Display Customer.io workspace information inside of the app UI

### ISSUE THREAD

**Issue by levibostian** [customerio/RemoteHabits-iOS#29]
Use case: Someone on the team opens up the app and is wondering what workspace the SDK is sending data to. Being able to view at runtime what workspace they are using would be helpful.

**Comment by levibostian** [comment]
This ticket is a part of https://github.com/customerio/RemoteHabits-iOS/issues/30

**Comment by ami-aman** [comment]
This task is done as a part of [#30 ](https://github.com/customerio/RemoteHabits-iOS/issues/30)
