### ISSUE TITLE
Create new Remote Habits app for iOS

### ISSUE THREAD

**Issue by ami-aman** [customerio/RemoteHabits-iOS#30]
Reference mockup designs
https://www.figma.com/file/BJdEVphP1xPOPFQcKkqNhk/Remote-Habits-App?node-id=137%3A304

**Comment by lj-cio** [comment]
Notes on Functionality:

* On Login, identify customer with the `name` as an attribute using the SDK (https://customer.io/docs/sdk/ios/identify/#identify).
* On Logout, stop identifying the customer using the SDK (https://customer.io/docs/sdk/ios/identify/#clearIdentify).
* On click of a "Habit", send event using the SDK with properties `name: Clicked Habit` and property `habit: <habit name>` (https://customer.io/docs/sdk/ios/track-events/#track-a-custom-event).
* On change of the toggle, number of times, time start, or time end for a "Habit", send event using the SDK with properties `name: Habit Updated` and properties `habit: <habit name>`, `frequency: <number of times>`, `start_time: <start time>`, `end_time: <end time>`.

**Comment by hownowstephen** [comment]
when changing site_id/api_key we can use the `dexterity-check` [endpoint](https://github.com/customerio/edge/blob/426634059656115ddcc4d702701a91b5b65b36f7/misc/router.go#L10) at the edge to validate the supplied creds, which is just doing a basic auth GET to https://track.customer.io/dexterity-check 

```
curl -XGET https://track.customer.io/dexterity-check -u siteid:apikey
```
