### ISSUE TITLE
Deep linking - Launch the app to the screen considering login status

### ISSUE THREAD

**Issue by ami-aman** [customerio/RemoteHabits-iOS#52]
Remote Habits app should be able to handle a scenario when the user receives a push notification with a custom flag to deep link and open the app to a specific screen. 

- Open Switch Workspace screen if value of link in custom payload is `remote-habits://switch_workspace?site_id=123&api_key=456`
- Get values of `site_id` and `api_key` from the link and pre-fill in the text fields in Switch Workspace screen
- If site_id and api_key is missing or the link is `remote-habits://switch_workspace` then show switch workspace screen with blank text fields
- If either of the values is missing then show switch workspace screen with blank text fields
- If user is **logged in** and push notification is tapped to open, then show Switch Workspace screen and 
   - if user taps back button or dismisses the screen then show Dashboard
   - if user taps Switch Workspace button then validate the credentials and logout the current profile and take the user to login screen
   - if user is on Dashboard detail screen then dismiss this screen and show Switch Workspace to the user with filled or unfilled values based on data received in the link
   - if Switch Workspace is already open then do nothing
- If user is **not logged in** and push notification is tapped to open, then show Switch Workspace screen and 
   - if user taps back button or dismisses the screen then show Login
   - if user taps Switch Workspace button then validate the credentials and bring the user to login screen

**Comment by Breadcorn** [comment]
> Remote Habits app should be able to handle a scenario when the user receives a push notification with a custom flag to deep link and open the app to a specific screen.
> 
> * Open Switch Workspace screen if value of link in custom payload is `remote-habits://switch_workspace?site_id=123&api_key=456`
> * Get values of `site_id` and `api_key` from the link and pre-fill in the text fields in Switch Workspace screen
> * If site_id and api_key is missing or the link is `remote-habits://switch_workspace` then show switch workspace screen with blank text fields
> * If either of the values is missing then show switch workspace screen with blank text fields
> * If user is **logged in** and push notification is tapped to open, then show Switch Workspace screen and
>   
>   * if user taps back button or dismisses the screen then show Dashboard
>   * if user taps Switch Workspace button then validate the credentials and logout the current profile and take the user to login screen
>   * if user is on Dashboard detail screen then dismiss this screen and show Switch Workspace to the user with filled or unfilled values based on data received in the link
>   * if Switch Workspace is already open then do nothing
> * If user is **not logged in** and push notification is tapped to open, then show Switch Workspace screen and
>   
>   * if user taps back button or dismisses the screen then show Login
>   * if user taps Switch Workspace button then validate the credentials and bring the user to login screen
